spring.application.name=tech-store-project

# PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/techstore_db
spring.datasource.username=admin_techstore
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in console (helps debug issues)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.techstore=DEBUG
